name = "ConnectedComponents"
uuid = "b17e3d47-dde4-4b75-9e4c-7f9b6a5f3d7f"
authors = ["Joseph Cummings <josephcummings03@gmail.com>"]
version = "0.1.0"

[deps]
HomotopyContinuation = "f213a82b-91d6-5c5d-acf7-10f1c761b327"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.10"
HomotopyContinuation = "2.10"
Reexport = "1.2.2"